# -*- coding: utf-8 -*-
"""Copy of if else in lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eua0Rg-kPcDU9EOyUv9aiUVQqixFLc-d
"""

student_scores= [89,76,63,91,55]
total_score=0
for score in student_scores:
  total_score+=score
print(total_score)

avg_score=total_score/len(student_scores)
print(avg_score)

print(max(student_scores))
print(min(student_scores))

median_score=student_scores[2]
print(median_score)

sorted_score=sorted(student_scores)
print(sorted_score)

num=len(student_scores)
print(num)

median_score=(len(student_scores)+1)/2
print(median_score)

print(sorted_score[2])

sorted_score=[55, 63, 76, 89, 91]
num=len(sorted_score)
if num%2==0:
  median=num/2
  print(median)
else:
  median1=(num+1)/2
  print(median1)

print(sorted_score[2])

